# Aggregate gate for Life Simulator. `make verify` must be green before any PR.
SHELL := /bin/bash
export PATH := $(HOME)/.cargo/bin:/opt/homebrew/opt/rustup/bin:$(PATH)
ENGINE := engine
WASM_OUT := app/assets/wasm
# Must match the `wasm-bindgen` crate version in engine/Cargo.lock: the CLI refuses a
# module generated by a different one.
WASM_BINDGEN_VERSION := 0.2.128

.PHONY: verify rails-verify engine-verify wasm schema test lint fmt

# The wasm build comes first: the viewer page imports its output, so the system specs
# need it on disk.
verify: wasm rails-verify engine-verify

rails-verify:
	bundle exec rubocop
	bundle exec brakeman -q --no-pager --no-exit-on-warn --no-exit-on-error
	bundle exec rspec

engine-verify:
	@if [ -f $(ENGINE)/Cargo.toml ]; then \
	  cd $(ENGINE) && cargo fmt --all -- --check && cargo clippy --workspace --all-targets -- -D warnings && cargo test --workspace; \
	else echo "engine/: not present yet, skipping"; fi

# Builds the wasm crate into app/assets/wasm/ (gitignored: the build is the source of
# truth, never the output). Propshaft serves life_engine.js and life_engine_bg.wasm from
# there. Needs `cargo install wasm-bindgen-cli --version $(WASM_BINDGEN_VERSION) --locked`.
wasm:
	@if [ ! -f $(ENGINE)/crates/wasm/Cargo.toml ]; then echo "wasm crate: not present yet, skipping"; exit 0; fi; \
	if ! command -v wasm-bindgen >/dev/null; then \
	  echo "wasm-bindgen $(WASM_BINDGEN_VERSION) is missing: cargo install wasm-bindgen-cli --version $(WASM_BINDGEN_VERSION) --locked"; \
	  exit 1; \
	fi; \
	rustup target add wasm32-unknown-unknown >/dev/null && \
	cd $(ENGINE) && cargo build -p wasm --target wasm32-unknown-unknown --release && cd .. && \
	wasm-bindgen --target web --no-typescript --out-name life_engine --out-dir $(WASM_OUT) \
	  $(ENGINE)/target/wasm32-unknown-unknown/release/wasm.wasm

# Refreshes the parameter schema Rails reads from the engine, its only authority.
schema:
	cd $(ENGINE) && cargo run -q -p runner -- schema > ../config/engine_schema.json

test: ; bundle exec rspec
lint: ; bundle exec rubocop -A
fmt:  ; cd $(ENGINE) && cargo fmt --all
