# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
# Generated by `make wasm` into app/assets/wasm/; the pin is skipped (and the viewer says
# so) when that build has not run.
pin "life_engine", to: "life_engine.js", preload: false
