[package]
name = "runner"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "runner"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5", features = ["derive"] }
life-engine.workspace = true
png = "0.17"
serde.workspace = true
serde_json.workspace = true
